### ISSUE TITLE
Compatibility with iOS9

### ISSUE THREAD

**Issue by frankobe** [google/gdata-objectivec-client#183]
A few functions have been depreciated in iOS 9
1. NSURLConnection Class
2. stringByAddingPercentEscapesUsingEncoding
3. CFURLCreateStringByAddingPercentEscapes

So current version can't compile successfully

**Comment by louis000** [comment]
is this compatibility issue with iOS9 resolved?

**Comment by thomasvl** [comment]
Greg is looking at updating things.  As the Readme mentions, the preferred path for most services is https://github.com/google/google-api-objectivec-client (the json apis).  So this library doesn't get much use and so we hadn't updated for Xcode 7/iOS 9 yet.

**Comment by louis000** [comment]
Great! Didn't know there is a preferred JSON API. Thank you for pointing it out.

Sent from Outlook




On Tue, Sep 22, 2015 at 8:08 AM -0700, "Thomas Van Lenten" <notifications@github.com> wrote:












Greg is looking at updating things.  As the Readme mentions, the preferred path for most services is https://github.com/google/google-api-objectivec-client (the json apis).  So this library doesn't get much use and so we hadn't updated for Xcode 7/iOS 9 yet.

**Comment by frankobe** [comment]
But how can I access contact api by json apis?

**Comment by louis000** [comment]
do you think it makes sense to move the XML based API to JSON based API and when do we expect to get the Xcode 7/IOS 9 compatible client library? Thank You!

**Comment by thomasvl** [comment]
Contacts is one of the few spots where I don't believe there is a json api.

**Comment by louis000** [comment]
Exactly! The contact API is the few spot that's still based on XML. However, many developers are still using this API library. Really appreciate if we can get this API library up and running.

Sent from Outlook




On Wed, Sep 23, 2015 at 8:14 AM -0700, "Thomas Van Lenten" <notifications@github.com> wrote:












Contacts is one of the few spots where I don't believe there is a json api.

**Comment by louis000** [comment]
how are things going thomasvl ?

**Comment by amarzulli** [comment]
Try this fix...
http://stackoverflow.com/questions/32615688/google-api-error-multiple-methods-named-initwitharray-found

Worked for me...hope it helps!

**Comment by louis000** [comment]
how are things going thomasvl ? are we expecting a new release soon?

**Comment by frankobe** [comment]
I suggest using google contact API directly, set "alt=json" in parameter can return json data. And then you can parse them locally. For authentication, set "Authorization = Bearer accessToken" in header.
