### ISSUE TITLE
Is this api deprecated for spreadsheet service ?

### ISSUE THREAD

**Issue by nicolaslauquin** [google/gdata-objectivec-client#184]
The api return an error which make thinks this api is not working anymore. Could you confirm ?

**To reproduce:** 
Run SpreadsheetSample, try to login:
Error Domain=com.google.GDataServiceDomain Code=404 "The operation couldn’t be completed. (com.google.GDataServiceDomain error 404.)"

**Comment by snakeninny** [comment]
@nicolaslauquin Have you solved the issue yet? I've encountered a similar one: Error Domain=com.google.GDataServiceDomain Code=404 "(null)"

**Comment by nicolaslauquin** [comment]
@snakeninny No answers since 4mois :(. Please keep me updated if you found a solution. Note: even the demo project have this issue.

**Comment by snakeninny** [comment]
@nicolaslauquin I think the Google Drive API is really vague. I've found at least 3 libraries/frameworks doing this, i.e. gdata-objectivec-client, google-api-objectivec-client and Apps script, but the first 2 seem to be outdated. I've followed Google's step to step instruction on the [Apps script one](https://developers.google.com/apps-script/guides/rest/quickstart/ios), but it fails to compile too. What surprises me is that there seems to be lots of developers having issues on this, and nearly none of them are solved. [This project](https://github.com/rehomik/googleSpreadSheetApiDemo) compiles but reports the above error, and I'm looking into it. If you're interested, we can work together to figure it out.

**Comment by nicolaslauquin** [comment]
@snakeninny The service seems cut on the server side, it used to work before, I had an application in production using this api and suddently it stopped working wihtout re-compile it. 

Note : I have also had a look at [Google Drive api](https://developers.google.com/drive/ios/), but it is not the same goal. 

So far I stopped looking for a solution but I'd be happy to know about your progress or solutions.

**Comment by thomasvl** [comment]
So while some of us work to help maintain the ObjC library, that doesn't mean we're up on all the services.  So we have to defer some things to the server teams that support the apis.  Having said that, it looks like the SpreadSheets api is still support by then with this GData api.  It looks like some of the developer support and server folks monitor questions on stackoverflow: http://stackoverflow.com/questions/tagged/google-spreadsheet-api, so maybe try posting your questions there.  They aren't as likely to know ObjC (or Swift), but you you use the built in logging (https://github.com/google/gdata-objectivec-client/wiki#logging-http-server-traffic), that should let you easily include requests/responses for them to see what is happening.
