### ISSUE TITLE
Xcode 7.3b4, non-arc, cannot create __weak reference

### ISSUE THREAD

**Issue by sanhue0302** [google/gdata-objectivec-client#189]
build failed because this issue
should fix declaration in GDataProgressMonitorInputStream

**Comment by sanhue0302** [comment]
sorry i think i get a wrong commit

**Comment by thomasvl** [comment]
Which services are you using GData with?  In most cases using https://github.com/google/google-api-objectivec-client would be a better choice (there are a few that only have GData interface)

**Comment by sanhue0302** [comment]
i still have a question 
if i use commit in master (bc22eeece64330205b97a42ed2702482c03d7081), there still have a __weak declaration,
so i use tag data-objectivec-client-1.12.0 to solve this problem
but what if i want to get most recently changes, how could i do?

**Comment by thomasvl** [comment]
We haven't cut a tag/release on this in a very long time and it doesn't get any active work because most of Google's apis are using JSON now instead.  You should be fine using master instead of a specific tag.

**Comment by sanhue0302** [comment]
so how should i do to get google's api using JSON?
i need access google contact and google photos
Is there any reference data?

**Comment by sanhue0302** [comment]
if i need to user master then the problem(non-arc, cannot create __weak reference) should be solved first

**Comment by thomasvl** [comment]
Re accessing contacts & photos – as mentioned in the project README.md, those server teams don't have JSON apis, so the XML apis (this project) are still the correct choice.

**Comment by sanhue0302** [comment]
this issue was fixed by 923adac5fa0129e36bfd69b63131ced89d792f87
