### ISSUE TITLE
Photos upload does not work anymore

### ISSUE THREAD

**Issue by mirkoevo** [google/gdata-objectivec-client#196]
Hi,

I don't know what changed recently in the service but I can't upload to Google Photos anymore.
I've tested with two accounts, with different errors.

In this account I have removed the grant from the google/account panel then reauthorized from the app:

2016-11-02 00:07:52.052 App[76491:28391588] serviceBase:<GDataServiceGooglePhotos: 0x6480001c1a40> objectFetcher:GTMSessionUploadFetcher 0x101da62f0 (https://photos.googleapis.com/data/upload/resumable/media/create-session/feed/api/user/114209999584000922529/albumid/6346618894798241153) failedWithStatus:503 data:

In the other I get an "invalid_grant" error.

I can get the album list, but I can't create albums or upload photos.

Same thing happens with current version and previous using HTTPSessionFetcher.

**Comment by thomasvl** [comment]
You likely will want to reach out to on that server API's support area: https://developers.google.com/picasa-web/forum  (since as you mention, you code and this libraries code haven't changed, so it likely is something server side that changed)

You might also want to capture a [http log](https://github.com/google/gdata-objectivec-client/wiki#logging-http-server-traffic) to help show what you are sending and is failing.

**Comment by mirkoevo** [comment]
I've tried, but my posts haven't been approved yet...

This is the log, and the response is quite eloquent... hope they haven't killed the service!

2016-11-04 10:48:14 +0000      GTMOAuth2 refresh fetch to www.googleapis.com for "***"      request/response log
elapsed: 0.406sec
request: POST https://www.googleapis.com/oauth2/v4/token
   headers: 2 
   data: 175 bytes, application/x-www-form-urlencoded
response:  status 200
   headers: 13 
   data: 973 bytes, application/json 
2016-11-04 10:48:14 +0000      addPhotoTicket:finishedWithEntry:error:      request/response log
elapsed: 0.857sec
request: POST https://photos.googleapis.com/data/upload/resumable/media/create-session/feed/api/user/default/albumid/default
   headers: 12    authorized
   data: 688 bytes, application/atom+xml; charset=utf-8
response:  status 503 service unavailable  ⚑
   headers: 7 
   data: 0 bytes, text/html

**Comment by mirkoevo** [comment]
After a couple of tests, I've downgraded my copy to use HTTPFetcher again, since I need 10.7 support, and it works again.

So it is not a problem of the google service, but there should be some glitches in SessionFetcher.

**Comment by thomasvl** [comment]
Thanks for the update.  If you've got an easy repo setup, it would be great to share so we can help take a look.
