### ISSUE TITLE
Getting No response from server 404

### ISSUE THREAD

**Issue by iOsMechanic** [google/gdata-objectivec-client#197]
Error Domain=com.google.GDataServiceDomain Code=404 "The operation couldn’t be completed. (com.google.GDataServiceDomain error 404.)"

**Comment by thomasvl** [comment]
Without more info, there really isn't any way to say what is wrong.  What are you trying to do?  Which client?  etc.  The fetchers have built in support for [logging](https://github.com/google/gdata-objectivec-client/wiki#logging-http-server-traffic), posting a failed request can help show what you are doing.

**Comment by iOsMechanic** [comment]
API authentication

2016-11-21 05:46:11 +0000  elapsed: 0.510sec
Request: POST https://www.google.com/accounts/ClientLogin
Request body: (131 bytes)
Email=shun%40gmail.com&Passwd=_snip_&source=com.example.SpreadsheetSample%2F1.0&service=wise&accountType=HOSTED_OR_GOOGLE

Response: status 404
Response headers:
  Alt-Svc: quic=":443"; ma=2592000; v="36,35,34"
  Cache-Control: no-cache, no-store
  Content-Length: 65
  Content-Type: text/plain
  Date: Mon, 21 Nov 2016 05:46:11 GMT
  Expires: Mon, 01-Jan-1990 00:00:00 GMT
  Pragma: no-cache
  Server: GSE
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block

Response body: (65 bytes)
https://developers.google.com/accounts/docs/AuthForInstalledApps

-----------------------------------------------------------

**Comment by thomasvl** [comment]
Client Login is no logger supported on Google properties, you need to do OAuth 2 flows.  https://github.com/google/gdata-objectivec-client/wiki#authentication-and-authorization

**Comment by iOsMechanic** [comment]
@thomasvl Could u post some gist/example on how to add Contacts coz the support for webviews are gone from server side and all sample code are obselete.
So could you share some example for google signin sdk?

**Comment by thomasvl** [comment]
Timing wise things[ just changed](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html), making this a little more complete.  You'll want to look at using https://github.com/google/GTMAppAuth.  It can create an authorizer that can be used with this library.  We're working through updating the samples in all the projects that used to use gtm-oauth2, but it isn't done yet.

**Comment by paul909090** [comment]
@thomasvl Is your update done today?

**Comment by thomasvl** [comment]
Looks like the teams have done some a few updates, but not all, and it doesn't like some that were done were pushed out.  I'll bug some folks.

**Comment by paul909090** [comment]
Ok thanks! Keep me in touch
