### ISSUE TITLE
GTMGatherInputStream.h: No such file or directory

### ISSUE THREAD

**Issue by AaoIi** [google/gdata-objectivec-client#205]
Hello, 

When trying to run the sample of GooglePhotos and after setting the signing certificates to be able to run it, I'm getting GTMGatherInputStream.h: No such file or directory. what should i do ?

**Comment by thomasvl** [comment]
When you did the git clone, was it recursive?  The `Deps` directory contains git modules reference to pull in dependencies, and if you don't have the sub projects, that could be the problem.

**Comment by AaoIi** [comment]
@thomasvl , i imported the Deps but manually, forgot to do it. Thanks
